 - type: web
    env: static
    name: face-recognition
    repo: https://github.com/shilishalopez/faceRecognition.git
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_GRAPHQL_HOST
        fromService:
          name: face-recognition-backend
          type: web
          property: host